### ISSUE TITLE
Final Code edits for new repo

### ISSUE THREAD

**Issue by gitpusha** [gelatodigital/gelato#1]
- [x] Finish DutchX actions

- [x] Make `actions` `action functions` `stateless`

- [x] Switch to gelato internal user proxy system

- [ ] Introduce executor-action whitelist so that executors can be safe against malicious actions and do not have to rely on gas refunds for their business model -> can safely operate various other business models
No whitelist needed for now.

- [x] Try out/discuss new execution model: `canExecute()` also needs to check `actionConditionsFulfilled` (e.g. ERC20 allowance logic) to mitigate against further `revert` causes during `execution`

- [x] Port `kyber trigger` over from diffusion hackathon repo

- [x] Port `dutchX auction cleared` trigger

**Comment by gitpusha** [comment]
This issue is the last part of the issue that I opened yesterday, in which I tracked the new repo opening and code transfer from old repo. This issue was lost in process of repo restructuring.

**Comment by gitpusha** [comment]
Update: only the actual `action functions` need to be `stateless` (not read from or write to state) - the `action contracts` themselves can have `state` such as the `actionGasStipend` and the `actionSelector`

**Comment by gitpusha** [comment]
Changelog
----------

BREAKING CHANGES
----
**Actions**

- ActionKyberTrade: we now pass kyber address to action function. This is a breaking change for the welltimed frontend as the frontend needs to encode the action payload.

**Comment by hilmarx** [comment]
> * ActionKyberTrade: we now pass kyber address to action function. This is a breaking change for the welltimed frontend as the frontend needs to encode the action payload.

Why not hard code it in the function or in a getter func? This opens up some vulnerabilities imo. UIs can fuck up and pass a wrong address, or even wore, an address which sends all the money to an attacker. These sort of risks should be limited by hardcoding everything in actions.

**Comment by gitpusha** [comment]
> Why not hard code it in the function or in a getter func? This opens up some vulnerabilities imo. UIs can fuck up and pass a wrong address, or even wore, an address which sends all the money to an attacker. These sort of risks should be limited by hardcoding everything in actions.

I agree - I just quickly added that for convenience ,  since addresses vary across testnets. But I will remove it. Safety over convenience. I guess we' ll have to manually edit hardcoded addresses in between different deployments and networks.
