### ISSUE TITLE
DutchX withdraw issue reminder

### ISSUE THREAD

**Issue by gitpusha** [gelatodigital/gelato#4]
the issue is that `claimAndWithdraw` automatically `claims` all funds from `sellerBalances[auctionIndex]` => this means that if we sold multiple times into the same auction and each of our claims also has its own chained `claimAndWithdraw` claims - the first one works, but all consecutive `claimAndWithdraw` claims fail due to this [line](https://github.com/gnosis/dx-contracts/blob/e671cb1949ade9f81fe07a07f3a05656bfdadf72/contracts/DutchExchange.sol#L516) in the DutchX contract. 

You can only claim 1 time from one auction - afterwards you always need to only withdraw.

**Comment by hilmarx** [comment]
@gitpusha lets close all dutchX related issues

**Comment by gitpusha** [comment]
fixed in 6de71572830515153d85fd425a0d215f073c9a71
